### ISSUE TITLE
Would love to include AngelList in the sources

### ISSUE THREAD

**Issue by angelocordon** [atipugin/findjobs#1]

**Comment by atipugin** [comment]
I thought about AngelList, but didn't find any api/rss feed for vacancies. Do they have it at all?)

**Comment by angelocordon** [comment]
bummer, looks like they're pulling the plug on it https://angel.co/api

Or at least, keeping it as non-commercial and stricter user

**Comment by atipugin** [comment]
Yep, it's impossible to use it for now (due access token/rate limits).
